INSERT INTO PS_IO_DB_PRIV_TBL (BIS_IO_GRANTEE
 ,SQLTABLENAME
 ,SELECT_FLAG
 ,UPDATE_FLAG
 ,DELETE_FLAG
 ,INSERT_FLAG) 
 SELECT IO_DB_GRANTEE
 ,SQLTABLENAME
 ,SELECT_FLAG
 ,UPDATE_FLAG
 ,DELETE_FLAG
 ,INSERT_FLAG 
  FROM PS_IO_USR_PRIV_VW;