INSERT INTO PS_BIS_DB_PRIV_TBL (BIS_DB_GRANTEE
 ,SQLTABLENAME
 ,BIS_DB_GRANTOR
 ,SELECT_FLAG
 ,UPDATE_FLAG
 ,DELETE_FLAG
 ,INSERT_FLAG) 
 SELECT BIS_DB_GRANTEE
 ,SQLTABLENAME
 ,BIS_DB_GRANTOR
 ,SELECT_FLAG
 ,UPDATE_FLAG
 ,DELETE_FLAG
 ,INSERT_FLAG 
  FROM PS_BIS_USR_PRIV_VW;